### ISSUE TITLE
ANDORID?

### ISSUE THREAD

**Issue by demur1** [Drum3X/xashserverinfo#2]
Does it work on Android? And if so how did you install it?

**Comment by Drum3X** [comment]
Yes it works on termux.

git clone https://github.com/Drum3X/xashserverinfo
cd xashserverinfo
apt install php
php xashserverinfo.php <ip> <port>

**Comment by Drum3X** [comment]
https://github.com/Drum3X/xashserverinfo/commit/f1b9c66295b97a98ffd561a9ce263d99219a4aac
